In [2]:
import pandas as pd

In [7]:
go_df = pd.read_excel('../data/HUMAN_9606_idmapping.xlsx')

go_df

,UniProtKB-AC,UniProtKB-ID,GeneID (EntrezGene),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,P31946,1433B_HUMAN,7529,NP_003395.1; NP_647539.1; XP_016883528.1,4507949; 377656702; 67464628; 1345590; 1034625...,2BQ0:A; 2BQ0:B; 2C23:A; 4DNK:A; 4DNK:B; 5N10:A...,GO:0005737; GO:0005829; GO:0070062; GO:0005925...,UniRef100_P31946,UniRef90_P31946,UniRef50_P31946,...,9606.0,601289,NaN,8515476; 14702039; 11780052; 15489334; 2357255...,X57346; AK292717; AL008725; CH471077; CH471077...,CAA40621.1; BAF85406.1; -; EAW75893.1; EAW7589...,ENSG00000166913.13,ENST00000353703.9; ENST00000372839.7,ENSP00000300161.4; ENSP00000361930.3,11996670; 12364343; 12437930; 12468542; 124825...
1,P62258,1433E_HUMAN,7531,NP_006752.1,374074368; 62131678; 67464424; 194379794; 2210...,2BR9:A; 3UAL:A; 3UBW:A; 6EIH:A; 7C8E:A; 7C8E:B,GO:0005737; GO:0005829; GO:0070062; GO:0005925...,UniRef100_P62258,UniRef90_P62258,UniRef50_P62258,...,9606.0,605066,NaN,7644510; 8858348; 8684458; 20417184; 14702039;...,U20972; U54778; U43399; U43430; U28936; AB0171...,AAC50175.1; AAC50710.1; AAC50625.1; AAD00026.1...,ENSG00000108953.17; ENSG00000274474.3,ENST00000264335.13; ENST00000571732.5; ENST000...,ENSP00000264335.8; ENSP00000461762.1; ENSP0000...,15838597; 11782387; 12657644; 14966136; 153649...
2,Q04917,1433F_HUMAN,7533,NP_003396.1,4507951; 437363; 83754686; 83754699; 83754700;...,2C63:A; 2C63:B; 2C63:C; 2C63:D; 2C74:A; 2C74:B...,GO:0150048; GO:0005737; GO:0005829; GO:0070062...,UniRef100_Q04917,UniRef90_Q04917,UniRef50_Q04917,...,9606.0,113508,NaN,8218406; 1578511; 8561965; 8812417; 15461802; ...,L20422; X80536; X78138; X57345; D78577; S80794...,AAA35483.1; CAA56676.1; CAA55017.1; CAA40620.1...,ENSG00000128245.15,ENST00000248975.6,ENSP00000248975.5,10206237; 11121172; 11996670; 12176995; 124801...
3,P61981,1433G_HUMAN,7532,NP_036611.2,6016838; 380764684; 635576381; 82407956; 82407...,2B05:A; 2B05:B; 2B05:C; 2B05:D; 2B05:E; 2B05:F...,GO:0005737; GO:0005829; GO:0070062; GO:0005925...,UniRef100_P61981,UniRef90_P61981,UniRef50_P61981,...,9606.0,605356; 617665,NaN,10433554; 10486217; 12853948; 15489334; 235725...,AF142498; AB024334; CR541904; CR541925; AC0063...,AAD48408.1; BAA85184.1; CAG46702.1; CAG46723.1...,ENSG00000170027.7,ENST00000307630.5,ENSP00000306330.3,11824616; 11996670; 12364343; 12482592; 150572...
4,P31947,1433S_HUMAN,2810,NP_006133.1,436408756; 306991738; 969812714; 350610438; 35...,1YWT:A; 1YWT:B; 1YZ5:A; 1YZ5:B; 3IQJ:A; 3IQU:A...,GO:0005737; GO:0005829; GO:0070062; GO:0005615...,UniRef100_P31947,UniRef90_P31947,UniRef50_P31947,...,9606.0,601290,NaN,1390337; 8515476; 9659898; 16710414; 15489334;...,M93010; X57348; AF029081; AF029082; CR541905; ...,AAA59546.1; CAA40623.1; AAC52029.1; AAC52030.1...,ENSG00000175793.12,ENST00000339276.6,ENSP00000340989.4,10969776; 12582028; 12730237; 12787309; 145172...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
207775,B4DID3,B4DID3_HUMAN,NaN,NaN,5410274; 194380584,NaN,NaN,UniRef100_B4DID3,UniRef90_Q8TF05,UniRef50_Q8TF05,...,9606.0,NaN,NaN,NaN,AK295533,BAG58445.1,NaN,NaN,NaN,20379614; 23084358; 25134449; 28445980; 32077156
207776,H9BQ89,H9BQ89_HUMAN,NaN,NaN,380261419,NaN,NaN,UniRef100_M9PA30,UniRef90_R4QU36,UniRef50_A0A8D1H387,...,9606.0,NaN,NaN,NaN,JQ048681,AFD36908.1,NaN,NaN,NaN,11069619; 11194889; 11556968; 12022360; 122967...
207777,H9C5H6,H9C5H6_HUMAN,NaN,NaN,380261481,NaN,NaN,UniRef100_H9C5H6,UniRef90_A0A7T8G1Q1,UniRef50_A0A2I3MMI5,...,9606.0,NaN,NaN,NaN,JQ237634,AFD36939.1,NaN,NaN,NaN,10332976; 10440244; 11291046; 11402452; 114260...
207778,Q9HAQ5,Q9HAQ5_HUMAN,NaN,NaN,10834833,NaN,GO:0004060,UniRef100_Q9HAQ5,UniRef90_A0A0D9SB19,UniRef50_P11245,...,9606.0,NaN,NaN,NaN,AF308866,AAG23842.1,NaN,NaN,NaN,10698485; 10817597; 10848734; 11291049; 114313...
207779,A0A186VNL2,A0A186VNL2_HUMAN,NaN,NaN,844316062,NaN,NaN,UniRef100_A0A7D8VDM9,UniRef90_P16210,UniRef50_P04439,...,9606.0,NaN,NaN,NaN,KR082290,AKN09128.1,NaN,NaN,NaN,NaN

In [8]:
go_df['GeneID (EntrezGene)']

0         7529
1         7531
2         7533
3         7532
4         2810
          ...
207775     NaN
207776     NaN
207777     NaN
207778     NaN
207779     NaN
Name: GeneID (EntrezGene), Length: 207780, dtype: object

In [9]:
label_df = pd.read_csv('../data/cpg0016/version_2023-06-14/gene_labels.csv')
label_df

,Metadata_Symbol,Metadata_NCBI_Gene_ID,Indeterminate,Negative,Positive,gene_label
0,A2M,2,1,1,3,Positive
1,A3GALT2,127550,1,0,4,Positive
2,A4GALT,53947,0,0,5,Positive
3,A4GNT,51146,3,0,3,Indeterminate
4,AACS,65985,1,0,4,Positive
...,...,...,...,...,...,...
7970,ZSCAN32,54925,4,0,1,Indeterminate
7971,ZSCAN4,201516,0,0,3,Positive
7972,ZSCAN5A,79149,0,0,5,Positive
7973,ZSCAN9,7746,0,0,5,Positive
7974,ZSWIM2,151112,1,0,4,Positive

In [10]:
go_df[go_df['GeneID (EntrezGene)'] == 53947]

,UniProtKB-AC,UniProtKB-ID,GeneID (EntrezGene),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
88,Q9NPC4,A4GAT_HUMAN,53947,NP_001304967.1; NP_059132.1; XP_005261701.1; X...,530420175; 25452796; 1034629093; 530420171; 76...,NaN,GO:0000139; GO:0016020; GO:0008375; GO:0008378...,UniRef100_Q9NPC4,UniRef90_Q9NPC4,UniRef50_Q9NPC4,...,9606.0,111400; 607922,NaN,10748143; 10747952; 15014171; 14702039; 105912...,AB037883; AJ245581; AB041418; AY941797; AK3129...,BAA95915.1; CAB93532.1; BAA94503.1; AAX20109.1...,ENSG00000128274.17,ENST00000249005.3; ENST00000381278.4; ENST0000...,ENSP00000249005.2; ENSP00000370678.3; ENSP0000...,11782470; 12888565; 18067504; 18757779; 191390...
57684,A0A0S2Z5J1,A0A0S2Z5J1_HUMAN,53947,NP_001304967.1; NP_059132.1; XP_005261701.1; X...,60459546; 15523687; 189066521; 957951157; 5304...,NaN,GO:0000139; GO:0050512; GO:0015643; GO:0001576,UniRef100_Q9NPC4,UniRef90_Q9NPC4,UniRef50_Q9NPC4,...,9606.0,NaN,NaN,26871637,KU178649,ALQ34107.1,NaN,NaN,NaN,11782470; 11896312; 12888565; 18067504; 187577...

In [11]:
go_subset = go_df[go_df['GeneID (EntrezGene)'].isin(label_df['Metadata_NCBI_Gene_ID'])]

In [18]:
go_terms = go_subset['Unnamed: 6'].str.split('; ')
go_terms

1         [GO:0005737, GO:0005829, GO:0070062, GO:000592...
3         [GO:0005737, GO:0005829, GO:0070062, GO:000592...
5         [GO:0005737, GO:0005829, GO:0070062, GO:000592...
9         [GO:0005813, GO:0000775, GO:0005737, GO:000582...
10        [GO:0005737, GO:0005829, GO:0005634, GO:000015...
                                ...
207620    [GO:0031012, GO:0016020, GO:0004222, GO:000827...
207677                             [GO:0000139, GO:0006891]
207709    [GO:0005829, GO:0045171, GO:0072686, GO:000565...
207730                             [GO:0046872, GO:0006355]
207748                                         [GO:0005634]
Name: Unnamed: 6, Length: 14773, dtype: object

In [22]:
gomap = pd.DataFrame({'Gene': go_subset['GeneID (EntrezGene)'], 'GO': go_terms}).explode('GO')
gomap

        Gene          GO
1       7531  GO:0005737
1       7531  GO:0005829
1       7531  GO:0070062
1       7531  GO:0005925
1       7531  GO:0042470
...      ...         ...
207709  3174  GO:0043565
207709  3174  GO:0008270
207730  7551  GO:0046872
207730  7551  GO:0006355
207748  9439  GO:0005634

[193564 rows x 2 columns]

In [29]:
gomat = gomap.pivot_table(index='Gene', columns='GO', aggfunc=lambda _:1, fill_value=0)

In [34]:
gomat.loc[7531,'GO:0005829']

1